# Generated by Django 3.2.5 on 2021-07-05 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoganApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 9, 37, 38, 325757), verbose_name='Start Date'),
        ),
    ]
