# Generated by Django 3.2.5 on 2021-07-05 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoganApp', '0002_conversation_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 5, 19, 432304), verbose_name='Start Date'),
        ),
    ]
