# Generated by Django 3.2.5 on 2021-07-05 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoganApp', '0003_alter_conversation_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timesent',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 14, 13, 29, 608336), verbose_name='Time Sent'),
        ),
        migrations.AddField(
            model_name='thought',
            name='timesent',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 14, 13, 29, 608336), verbose_name='Time Sent'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 14, 13, 29, 607338), verbose_name='Start Date'),
        ),
    ]
