# Generated by Django 3.2.5 on 2021-07-08 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoganApp', '0004_auto_20210705_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 14, 3, 38, 125054), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timesent',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 14, 3, 38, 126020), verbose_name='Time Sent'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='timesent',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 14, 3, 38, 126020), verbose_name='Time Sent'),
        ),
    ]
